In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('mushrooms.csv')

In [4]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [5]:
df.shape

(8124, 23)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
le = LabelEncoder()

In [9]:
ds = df.apply(le.fit_transform)

In [10]:
ds

class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
5         0          5            3          9        1     0   
6         0          0            2          8        1     0   
7         0          0            3          8        1     3   
8         1          5            3          8        1     6   
9         0          0            2          9        1     0   
10        0          5            3          9        1     3   
11        0          5            3          9        1     0   
12        0          0            2          9        1     0   
13        1          5            3          8        1     6   
14        0          5            0          4        0     5   
15        0          4            0          3        0     5   
16        0          2            0          8        0     5   
17        1          5            2          4        1     6   
18        1          5            3          8        1     6   
19        1          5            2          4        1     6   
20        0          0            2          9        1     0   
21        1          5            3          4        1     6   
22        0          0            3          9        1     3   
23        0          0            3          8        1     0   
24        0          0            2          8        1     3   
25        1          2            2          8        1     6   
26        0          5            3          9        1     0   
27        0          5            3          8        1     3   
28        0          2            0          4        0     5   
29        0          5            2          9        1     0   
...     ...        ...          ...        ...      ...   ...   
8094      0          0            2          3        0     5   
8095      1          5            3          1        0     4   
8096      0          3            0          8        0     5   
8097      1          3            3          4        0     7   
8098      1          3            2          2        0     8   
8099      0          3            0          8        0     5   
8100      0          2            2          4        0     5   
8101      1          3            2          2        0     7   
8102      0          5            2          4        0     5   
8103      0          3            2          4        0     5   
8104      0          3            2          4        0     5   
8105      0          3            2          4        0     5   
8106      0          3            2          4        0     5   
8107      0          5            2          4        0     5   
8108      1          3            3          2        0     8   
8109      0          0            2          8        0     5   
8110      0          5            2          4        0     5   
8111      0          3            2          8        0     5   
8112      0          3            2          4        0     5   
8113      1          3            3          2        0     8   
8114      1          2            3          1        0     4   
8115      0          5            2          4        0     5   
8116      1          3            3          4        0     7   
8117      1          3            2          2        0     8   
8118      1          3            3          4        0     2   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2      

In [14]:
data = ds.values
print(data[:,1])

[5 5 0 ... 2 3 5]


In [19]:
data_X = data[:,1:]

In [16]:
data_X

array([[5, 2, 4, ..., 2, 3, 5],
       [5, 2, 9, ..., 3, 2, 1],
       [0, 2, 8, ..., 3, 2, 3],
       ...,
       [2, 2, 4, ..., 0, 1, 2],
       [3, 3, 4, ..., 7, 4, 2],
       [5, 2, 4, ..., 4, 1, 2]])

In [17]:
data_X.shape

(8124, 22)

In [20]:
data_Y = data[:,0]

In [21]:
data_Y

array([1, 0, 0, ..., 0, 1, 0])

In [22]:
 x_train, x_test, y_train, y_test = train_test_split(data_X, data_Y, test_size = 0.2)

In [23]:
np.unique(y_train)

array([0, 1])

In [27]:
def prior_prob(y_train, label):
    total = y_train.shape[0]
    class_examples = np.sum(y_train == label)
    return (class_examples) / float(total)

In [25]:
Y = np.array([0,1,0, 1,0,0,1,1,1,1])

In [29]:
prior_prob(Y,1)

0.6

In [42]:
def cond_prob(x_train, y_train, feature_col, feature_val, label):
    x_filtered = x_train[y_train == label]
    generator = np.sum(x_filtered[:, feature_col] == feature_val)
    denominator = np.sum(y_train == label)
    return generator / float(denominator)

In [46]:
def predict(x_train, y_train, xtest):
    classes = np.unique(y_train)
    n_features = x_train.shape[1]
    posterior_proba = []
    for label in classes:
        likehood = 1
        for f in range(n_features):
            conditional = cond_prob(x_train, y_train,f, xtest[f], label)
            likehood = likehood * conditional
        prior = prior_prob(y_train, label)
        post = likehood * prior
        posterior_proba.append(post)
    pred = np.argmax(posterior_proba)
    return pred

In [61]:
print(x_test[100])

[2 2 2 0 2 1 0 1 0 1 0 2 2 7 6 0 2 1 0 7 4 2]


In [62]:
output = predict(x_train, y_train, x_test[100])

In [63]:
print(output)

1


In [60]:
print(y_test[100])

1


In [69]:
def score(x_train, y_train, x_test, y_test):
    pred= []
    for i in range(x_test.shape[0]):
        pred_label = predict(x_train, y_train, x_test[i])
        pred.append(pred_label)
    pred = np.array(pred)
    accuracy = np.sum(pred == y_test)/y_test.shape[0]
    return accuracy

In [70]:
print(score(x_train, y_train, x_test,y_test))

0.9975384615384615
